export type ExamQuestionType = 'single' | 'multiple' | 'truefalse'

export interface ExamOption {
  id: string
  text: string
}

export interface ExamQuestion {
  id: number
  section: 'A' | 'B' | 'C' | 'D' | 'E'
  sectionTitle: string
  type: ExamQuestionType
  prompt: string
  options?: ExamOption[]
  /** single: option id; multiple: option ids; truefalse: true=对 false=错 */
  correct: string | string[] | boolean
  explanation: string
  points: number
}

export interface ExamMeta {
  id: string
  title: string
  subtitle: string
  version: string
  totalPoints: number
  passScore: number
  questionCount: number
  disclaimer: string
}

export const gutCareExamMeta: ExamMeta = {
  id: 'gut-care',
  title: '轻症便秘·痔疮·术后护理 自测',
  subtitle: '病友互助 / 志愿者培训 · 非医学资格考试',
  version: 'v1.0',
  totalPoints: 100,
  passScore: 80,
  questionCount: 30,
  disclaimer:
    '本试题检验 CommonBody 整理的患者经验与日常护理常识，不构成医疗考试，不能替代医生诊断。重症（大出血、剧痛、肿物嵌顿、高热等）不适用本卷经验，必须就医。',
}

export const gutCareExamQuestions: ExamQuestion[] = [
  {
    id: 1,
    section: 'A',
    sectionTitle: '就医边界与红线',
    type: 'single',
    prompt: '下列哪种情况应立即就医，而不是仅靠居家护理？',
    options: [
      { id: 'a', text: '偶尔一天没排便，腹胀不明显' },
      { id: 'b', text: '轻微肛裂，排便时短暂刺痛，无大量出血' },
      { id: 'c', text: '大量便血、流血不止，或肿物脱出无法回纳' },
      { id: 'd', text: '久坐后肛门轻微不适，休息后缓解' },
    ],
    correct: 'c',
    explanation: '大出血、嵌顿等为急诊/就医指征。',
    points: 4,
  },
  {
    id: 2,
    section: 'A',
    sectionTitle: '就医边界与红线',
    type: 'single',
    prompt: 'CommonBody 护理指南的适用人群主要是？',
    options: [
      { id: 'a', text: '所有肛肠疾病患者，包括重症和嵌顿痔' },
      { id: 'b', text: '仅术后第一周住院患者' },
      { id: 'c', text: '轻症便秘、轻微痔疮、肛裂及术后恢复期的日常参考' },
      { id: 'd', text: '可替代肛肠科门诊诊断' },
    ],
    correct: 'c',
    explanation: '本站定位轻症与日常护理参考。',
    points: 4,
  },
  {
    id: 3,
    section: 'A',
    sectionTitle: '就医边界与红线',
    type: 'truefalse',
    prompt: '「做过痔疮手术就一劳永逸，以后不用管作息和饮食。」',
    correct: false,
    explanation: '作者六次手术教训：术后仍须长期管理习惯。',
    points: 4,
  },
  {
    id: 4,
    section: 'A',
    sectionTitle: '就医边界与红线',
    type: 'truefalse',
    prompt: '在抖音群或互助群里，病友可以互相推荐具体医院套餐、药品链接来「帮忙」。',
    correct: false,
    explanation: '禁止推销药品、医院套餐。',
    points: 4,
  },
  {
    id: 5,
    section: 'A',
    sectionTitle: '就医边界与红线',
    type: 'multiple',
    prompt: '以下哪些表述符合 CommonBody 的合规分享原则？（多选）',
    options: [
      { id: 'a', text: '「我当时的做法是每天喝一颗猕猴桃，对我有帮助」' },
      { id: 'b', text: '「这个方子根治痔疮，百分百有效」' },
      { id: 'c', text: '「术后我休息了两天，便软了一些，疼痛减轻——因人而异」' },
      { id: 'd', text: '「不买课、不带货，只是个人经验分享」' },
      { id: 'e', text: '「重症请就医，本内容仅供参考」' },
    ],
    correct: ['a', 'c', 'd', 'e'],
    explanation: 'B 属于夸大疗效违规表述。',
    points: 4,
  },
  {
    id: 6,
    section: 'B',
    sectionTitle: '便秘预防与饮食',
    type: 'single',
    prompt: '根据本站水果类建议，效果相对更明显、建议优先搭配的是？',
    options: [
      { id: 'a', text: '香蕉，每天 5～6 个' },
      { id: 'b', text: '猕猴桃、百香果，每天 3～5 个' },
      { id: 'c', text: '西瓜，越多越好' },
      { id: 'd', text: '只吃水果，不用吃饭' },
    ],
    correct: 'b',
    explanation: '见护理指南「水果类」分节。',
    points: 3,
  },
  {
    id: 7,
    section: 'B',
    sectionTitle: '便秘预防与饮食',
    type: 'single',
    prompt: '关于 100% 鲜榨橙汁，作者经验的建议用量是？',
    options: [
      { id: 'a', text: '每天 100 毫升' },
      { id: 'b', text: '每天 500 毫升' },
      { id: 'c', text: '每周 500 毫升' },
      { id: 'd', text: '必须空腹喝 1 升' },
    ],
    correct: 'b',
    explanation: '作者 2025 年经验。',
    points: 3,
  },
  {
    id: 8,
    section: 'B',
    sectionTitle: '便秘预防与饮食',
    type: 'single',
    prompt: '下列哪组食材属于本站「餐食推荐」中常提到的润肠搭配？',
    options: [
      { id: 'a', text: '炸鸡、奶茶、烧烤' },
      { id: 'b', text: '海带、秋葵、山药、木耳菜、丝瓜' },
      { id: 'c', text: '仅白粥咸菜' },
      { id: 'd', text: '只吃辣椒开胃' },
    ],
    correct: 'b',
    explanation: '见护理指南「餐食推荐」分节。',
    points: 3,
  },
  {
    id: 9,
    section: 'B',
    sectionTitle: '便秘预防与饮食',
    type: 'truefalse',
    prompt: '作者吃羊肉时的经验是：肉要高压锅压熟，并搭配胡萝卜，一口肉一口菜，否则容易便秘。',
    correct: true,
    explanation: '作者「腐竹炖羊肉」教训。',
    points: 3,
  },
  {
    id: 10,
    section: 'B',
    sectionTitle: '便秘预防与饮食',
    type: 'single',
    prompt: '作者多次犯病与便秘相关的共同教训不包括？',
    options: [
      { id: 'a', text: '新鲜水果和优质蛋白摄入不足' },
      { id: 'b', text: '没有养成规律的一天一次排便习惯' },
      { id: 'c', text: '大便偏硬导致轻微肛裂' },
      { id: 'd', text: '每天必吃三种以上保健品' },
    ],
    correct: 'd',
    explanation: '作者强调的是饮食、作息，非保健品。',
    points: 2,
  },
  {
    id: 11,
    section: 'B',
    sectionTitle: '便秘预防与饮食',
    type: 'multiple',
    prompt: '下列哪些习惯有助于预防便秘？（多选）',
    options: [
      { id: 'a', text: '保证睡眠，少熬夜' },
      { id: 'b', text: '超负荷劳累后及时休息' },
      { id: 'c', text: '长期久坐不动、不喝水' },
      { id: 'd', text: '膳食纤维和水果适量跟上' },
      { id: 'e', text: '硬便时反复用力久蹲' },
    ],
    correct: ['a', 'b', 'd'],
    explanation: 'C、E 易加重便秘。',
    points: 3,
  },
  {
    id: 12,
    section: 'B',
    sectionTitle: '便秘预防与饮食',
    type: 'single',
    prompt: '关于香蕉通便，本站说明是？',
    options: [
      { id: 'a', text: '效果非常明显，应替代猕猴桃' },
      { id: 'b', text: '可作为补充，但个体效果差异较大，不算最明显' },
      { id: 'c', text: '完全无效，禁止食用' },
      { id: 'd', text: '必须每天吃 10 根' },
    ],
    correct: 'b',
    explanation: '香蕉效果个体差异大。',
    points: 3,
  },
  {
    id: 13,
    section: 'C',
    sectionTitle: '轻微痔疮日常护理',
    type: 'single',
    prompt: '茶饮类建议中，正确的做法是？',
    options: [
      { id: 'a', text: '雪菊花、胖大海、罗汉果、龟苓膏粉每天同时喝' },
      { id: 'b', text: '四种方式每天任选其一，不宜叠加多种' },
      { id: 'c', text: '茶饮可以替代喝水' },
      { id: 'd', text: '孕妇哺乳期可随意加大用量' },
    ],
    correct: 'b',
    explanation: '茶饮每天任选其一。',
    points: 4,
  },
  {
    id: 14,
    section: 'C',
    sectionTitle: '轻微痔疮日常护理',
    type: 'single',
    prompt: '雪菊花日常参考用量是？',
    options: [
      { id: 'a', text: '每天 1 颗' },
      { id: 'b', text: '每天 5～10 颗' },
      { id: 'c', text: '一周 1 个' },
      { id: 'd', text: '每天 50 颗' },
    ],
    correct: 'b',
    explanation: '雪菊花 5～10 颗/天。',
    points: 3,
  },
  {
    id: 15,
    section: 'C',
    sectionTitle: '轻微痔疮日常护理',
    type: 'single',
    prompt: '作者在实践中总结的提肛运动参考量是？',
    options: [
      { id: 'a', text: '每组 10 个，每周 1 次' },
      { id: 'b', text: '每组 100～200 个，每天 3～5 组' },
      { id: 'c', text: '每天 1 组，每组 5 个' },
      { id: 'd', text: '用力越大越好，做到疼为止' },
    ],
    correct: 'b',
    explanation: '作者南宁时期经验。',
    points: 3,
  },
  {
    id: 16,
    section: 'C',
    sectionTitle: '轻微痔疮日常护理',
    type: 'single',
    prompt: '关于久坐，本站生活习惯建议是？',
    options: [
      { id: 'a', text: '连续坐 4 小时中间不用动' },
      { id: 'b', text: '久坐超过 1 小时，需要走动 5 分钟' },
      { id: 'c', text: '必须全程站立办公' },
      { id: 'd', text: '久坐没关系，只要提肛就行' },
    ],
    correct: 'b',
    explanation: '久坐超 1 小时走动 5 分钟。',
    points: 3,
  },
  {
    id: 17,
    section: 'C',
    sectionTitle: '轻微痔疮日常护理',
    type: 'multiple',
    prompt: '作者经验中，哪些因素容易诱发或加重痔疮反复？（多选）',
    options: [
      { id: 'a', text: '熬夜' },
      { id: 'b', text: '一天内长途劳累、饮酒吃辣' },
      { id: 'c', text: '冬天穿过多保暖裤压迫血管' },
      { id: 'd', text: '规律睡眠、适度活动' },
      { id: 'e', text: '搬重物、劈柴时不节省力气' },
    ],
    correct: ['a', 'b', 'c', 'e'],
    explanation: 'D 为保护性因素。',
    points: 4,
  },
  {
    id: 18,
    section: 'C',
    sectionTitle: '轻微痔疮日常护理',
    type: 'truefalse',
    prompt:
      '痔疮属于肠道末端炎症时，小肠、大肠内部往往也可能已有炎症，护理要兼顾整体肠道与便秘预防。',
    correct: true,
    explanation: '见护理指南模块概述说明。',
    points: 3,
  },
  {
    id: 19,
    section: 'D',
    sectionTitle: '术后护理',
    type: 'single',
    prompt: '作者第六次手术后，大约养了多久才排便不太痛？',
    options: [
      { id: 'a', text: '3 天' },
      { id: 'b', text: '1 周' },
      { id: 'c', text: '约 2 个月' },
      { id: 'd', text: '当天即可剧烈运动' },
    ],
    correct: 'c',
    explanation: '第六次术后约 2 个月排便不痛。',
    points: 4,
  },
  {
    id: 20,
    section: 'D',
    sectionTitle: '术后护理',
    type: 'single',
    prompt: '术后或肛裂轻症恢复期间，下列哪项更符合作者经验？',
    options: [
      { id: 'a', text: '立刻加班熬夜，无所谓' },
      { id: 'b', text: '只吃干硬辛辣食物刺激肠道' },
      { id: 'c', text: '多休息，便软、减摩擦，配合水果与温和饮食' },
      { id: 'd', text: '用力排便把堵住的便块一次拉完' },
    ],
    correct: 'c',
    explanation: '休息+软便+温和饮食。',
    points: 3,
  },
  {
    id: 21,
    section: 'D',
    sectionTitle: '术后护理',
    type: 'single',
    prompt: '关于术后/日常坐姿，作者长期经验是？',
    options: [
      { id: 'a', text: '越软的沙发越好' },
      { id: 'b', text: '尽量硬板凳；若只能坐软椅，可在臀下垫约 2.5 厘米厚的书' },
      { id: 'c', text: '必须跷二郎腿' },
      { id: 'd', text: '术后第一周即可长途开车 8 小时' },
    ],
    correct: 'b',
    explanation: '硬板凳、垫书为作者长期做法。',
    points: 3,
  },
  {
    id: 22,
    section: 'D',
    sectionTitle: '术后护理',
    type: 'single',
    prompt: '智能马桶冲洗的主要好处是？',
    options: [
      { id: 'a', text: '替代手术' },
      { id: 'b', text: '减少纸张摩擦伤害，清洁更舒适' },
      { id: 'c', text: '可以诊断痔疮分期' },
      { id: 'd', text: '必须每天冲洗 10 次才有效' },
    ],
    correct: 'b',
    explanation: '减少摩擦，非治疗手段。',
    points: 3,
  },
  {
    id: 23,
    section: 'D',
    sectionTitle: '术后护理',
    type: 'truefalse',
    prompt: '术后恢复只要伤口外观好了，就可以马上喝酒、吃辣、熬夜，不用过渡期。',
    correct: false,
    explanation: '术后需过渡期，忌酒辣熬夜。',
    points: 3,
  },
  {
    id: 24,
    section: 'D',
    sectionTitle: '术后护理',
    type: 'multiple',
    prompt: '作者轻度肛裂发作后，采取过的做法包括？（多选）',
    options: [
      { id: 'a', text: '多休息' },
      { id: 'b', text: '买水果、龟苓膏配蜂蜜牛奶' },
      { id: 'c', text: '必要时使用消炎药（遵医嘱）' },
      { id: 'd', text: '立刻再做一次手术' },
      { id: 'e', text: '之后改吃羊肉必用高压锅、配胡萝卜' },
    ],
    correct: ['a', 'b', 'c', 'e'],
    explanation: '作者轻度肛裂一周恢复经历；D 错误。',
    points: 4,
  },
  {
    id: 25,
    section: 'E',
    sectionTitle: '综合情景题',
    type: 'single',
    prompt: '病友小李术后第 3 天，排便时鲜血滴落不止，头晕乏力。你应该建议他？',
    options: [
      { id: 'a', text: '多喝雪菊花，再观察一周' },
      { id: 'b', text: '在群里问大家用什么药膏' },
      { id: 'c', text: '立即去医院急诊/肛肠科' },
      { id: 'd', text: '做 200 个提肛运动' },
    ],
    correct: 'c',
    explanation: '术后大量出血必须就医。',
    points: 4,
  },
  {
    id: 26,
    section: 'E',
    sectionTitle: '综合情景题',
    type: 'single',
    prompt: '办公室文员小王久坐 3 小时不动，最近便秘加肛门坠胀。最符合本站建议的第一步是？',
    options: [
      { id: 'a', text: '购买微商痔疮套餐' },
      { id: 'b', text: '每小时起来走动约 5 分钟，并检查睡眠、水果、饮水' },
      { id: 'c', text: '每天四种茶饮一起喝' },
      { id: 'd', text: '请假在家躺 1 个月不动' },
    ],
    correct: 'b',
    explanation: '久坐+生活方式调整优先。',
    points: 3,
  },
  {
    id: 27,
    section: 'E',
    sectionTitle: '综合情景题',
    type: 'single',
    prompt: '术后第 2 周的张先生想吃炖肉，较符合作者教训的做法是？',
    options: [
      { id: 'a', text: '羊肉不压烂，只吃大肉块' },
      { id: 'b', text: '肉类压熟煮透，搭配胡萝卜等蔬菜，避免只吃肉不吃菜' },
      { id: 'c', text: '配白酒助消化' },
      { id: 'd', text: '不吃任何蛋白质' },
    ],
    correct: 'b',
    explanation: '肉类压熟+蔬菜搭配。',
    points: 3,
  },
  {
    id: 28,
    section: 'E',
    sectionTitle: '综合情景题',
    type: 'single',
    prompt: '志愿者准备在群里分享护理经验，以下哪种话术符合合规分享原则？',
    options: [
      { id: 'a', text: '「你别去医院了，照我说的做一定好」' },
      { id: 'b', text: '「便秘时我试过猕猴桃+多喝水，对我有用，因人而异」' },
      { id: 'c', text: '「加微信买我的坐垫，根治痔疮」' },
      { id: 'd', text: '「出血多、剧痛请先就医」' },
    ],
    correct: 'b',
    explanation: 'B 为个人经验语气、合规；A 劝阻就医，C 推销导流。',
    points: 4,
  },
  {
    id: 29,
    section: 'E',
    sectionTitle: '综合情景题',
    type: 'truefalse',
    prompt:
      '病友说：「我肿物脱出 2 天了，用手塞不回去，疼得睡不着，但不想麻烦医生。」你应该建议他尽快就医，而不是只在群里交流饮食。',
    correct: true,
    explanation: '嵌顿样症状不能仅网聊。',
    points: 3,
  },
  {
    id: 30,
    section: 'E',
    sectionTitle: '综合情景题',
    type: 'multiple',
    prompt: '作者 2013 年后十几年未再手术，靠日常调整稳住。下列哪些属于其长期主线？（多选）',
    options: [
      { id: 'a', text: '保证营养（水果、优质蛋白）' },
      { id: 'b', text: '保证睡眠，少熬夜' },
      { id: 'c', text: '养成一天一次排便习惯' },
      { id: 'd', text: '知道便秘、上火后哪些水果/茶饮对自己有用' },
      { id: 'e', text: '完全不看医生、不看任何医学资料' },
    ],
    correct: ['a', 'b', 'c', 'd'],
    explanation: '作者文末五条主线；E 错误（作者也查过知网论文）。',
    points: 3,
  },
]
